name: oauth_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:
environment:
  sdk: ^3.6.0-122.0.dev
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  rexios_lints: ^8.0.0

flutter:
